import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import ChallengeList from "../components/ChallangeList";
import Footer from "../components/Footer";
import { challenges } from "../data/challenges";
import { techStack } from "../data/techstack";

export default function Home() {
  return (
    <div>
      {console.log("hallo")}
      <Head>
        <title>challenges :: schman.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className="bg-slate-50 border-t-4f border-cyan-600 min-h-screen text-gray-700 font-poppins font-light">
        <Header />
        <Hero />
        <ChallengeList challenges={challenges} />
        <Footer techstack={techStack} />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return { props: { challenges, techStack } };
}
