import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import ChallengeList from "../components/ChallangeList";
import Footer from "../components/Footer";

export default function Home({ challenges }) {
  return (
    <div>
      <Head>
        <title>challenges :: schman.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className="bg-slate-50 border-t-4f border-cyan-600 min-h-screen text-gray-700 font-poppins font-light">
        <Header />
        <Hero />
        <ChallengeList challenges={challenges} />
        <Footer />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  try {
    const baseUrl = process.env.PUBLIC_URL || "http://localhost:3000";
    const response = await fetch(`${baseUrl}/api/challenges`);
    const challenges = await response.json();

    return {
      props: {
        challenges,
      },
    };
  } catch (error) {
    console.error(error);
  }
}
